-- Tạo và cập nhật quyền cho Biên tập chi nhánh (tenant_editor)
-- Được quản lý bài viết, sự kiện, media
DELETE FROM public.role_permissions WHERE role = 'tenant_editor';

INSERT INTO
    public.role_permissions (
        role,
        resource,
        can_create,
        can_read,
        can_update,
        can_delete
    )
VALUES (
        'tenant_editor',
        'news',
        true,
        true,
        true,
        true
    ),
    (
        'tenant_editor',
        'events',
        true,
        true,
        true,
        true
    ),
    (
        'tenant_editor',
        'media',
        true,
        true,
        true,
        true
    ),
    (
        'tenant_editor',
        'users',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_editor',
        'transactions',
        false,
        false,
        false,
        false
    ),
    (
        'tenant_editor',
        'registrations',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_editor',
        'settings',
        false,
        false,
        false,
        false
    ),
    (
        'tenant_editor',
        'analytics',
        false,
        false,
        false,
        false
    ),
    (
        'tenant_editor',
        'tenants',
        false,
        false,
        false,
        false
    );

-- Tạo và cập nhật quyền cho Kế toán chi nhánh (tenant_accountant)
-- Đóng vai trò cực kỳ nhạy cảm, KHÔNG BỊ XÓA (Delete) quỹ Thanh toán
DELETE FROM public.role_permissions WHERE role = 'tenant_accountant';

INSERT INTO
    public.role_permissions (
        role,
        resource,
        can_create,
        can_read,
        can_update,
        can_delete
    )
VALUES (
        'tenant_accountant',
        'transactions',
        true,
        true,
        true,
        false
    ), -- TUYỆT ĐỐI KHÔNG SET can_delete = true
    (
        'tenant_accountant',
        'analytics',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_accountant',
        'registrations',
        false,
        true,
        true,
        false
    ),
    (
        'tenant_accountant',
        'news',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_accountant',
        'events',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_accountant',
        'media',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_accountant',
        'users',
        false,
        true,
        false,
        false
    ),
    (
        'tenant_accountant',
        'settings',
        false,
        false,
        false,
        false
    ),
    (
        'tenant_accountant',
        'tenants',
        false,
        false,
        false,
        false
    );